### ISSUE TITLE
jetpack

### ISSUE THREAD

**Issue by MAGICXQY** [NVIDIA-AI-IOT/cuDLA-samples#1]
When reading the README, I found that the version of jetpack is required to be 5.0.2, but the current version of nvidia's jetpack is 5.2, I would like to know whether it is the official update of 6.0 jetack

**Comment by mchi-zg** [comment]
Sorry! Didn't get your point. You can run it on the latest Jetpack - Jetpack 5.1.2.
https://developer.nvidia.com/embedded/jetpack-archive

**Comment by zerollzeng** [comment]
Please apply the trtexec patch under data/, more details can be found in the README
