### ISSUE TITLE
Quantization of yolov5

### ISSUE THREAD

**Issue by zifeiyu-tan** [NVIDIA-AI-IOT/cuDLA-samples#11]
If i only want to quantize with int8 in yolov5, how to change this code。

**Comment by liuanqi-libra7** [comment]
Hi @tangxiangyu0313 ,

The code in this [link](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/tree/main/export/yolov5-qat) has already implemented quantization for YOLOv5.
We provide two quantization modes for selection, and you can refer to the[ README](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/blob/main/export/README.md) for replication.

Thanks
