### ISSUE TITLE
how to test inference time

### ISSUE THREAD

**Issue by ou525** [NVIDIA-AI-IOT/cuDLA-samples#24]
i try use chrono,but when i print the time, get 0.

![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/23331359/1f2fea93-54b6-45ce-a43f-e9958e8ee483)

**Comment by yunyao2011800** [comment]
auto start0 = std::chrono::system_clock::now();
        cv::Mat one_img = cv::imread(image_path);
        bgr_imgs.push_back(one_img);
        std::vector<cv::Mat> nchwMats = yolov5_infer.preProcess4Validate(bgr_imgs);

        yolov5_infer.infer();
        results = yolov5_infer.postProcess4Validation(0.25, 0.5f);
        printf("Num object detect: %ld\n", results.size());
        for (auto &item : results)
        {
            // left, top, right, bottom, label, confident
            cv::rectangle(one_img, cv::Point(item[0], item[1]), cv::Point(item[2], item[3]), cv::Scalar(0, 255, 0), 2, 16);
        }
        auto end0 = std::chrono::system_clock::now();
        std::cout << "detect image time: " << std::chrono::duration_cast<std::chrono::milliseconds>(end0- start0).count() << "ms" << std::endl;

**Comment by ou525** [comment]
> ```
>     auto start0 = std::chrono::system_clock::now();
>     cv::Mat one_img = cv::imread(image_path);
>     bgr_imgs.push_back(one_img);
>     std::vector<cv::Mat> nchwMats = yolov5_infer.preProcess4Validate(bgr_imgs);
> 
>     yolov5_infer.infer();
>     results = yolov5_infer.postProcess4Validation(0.25, 0.5f);
>     printf("Num object detect: %ld\n", results.size());
>     for (auto &item : results)
>     {
>         // left, top, right, bottom, label, confident
>         cv::rectangle(one_img, cv::Point(item[0], item[1]), cv::Point(item[2], item[3]), cv::Scalar(0, 255, 0), 2, 16);
>     }
>     auto end0 = std::chrono::system_clock::now();
>     std::cout << "detect image time: " << std::chrono::duration_cast<std::chrono::milliseconds>(end0- start0).count() << "ms" << std::endl;
> ```

I modified the code with reference to this and added this code to multiple loops. I found that the printing time is getting longer and longer. I don’t know where the problem is.
for(int k=0;k< 1;k++)
{
			auto start0 = std::chrono::steady_clock::now();
			cv::Mat one_img = cv::imread(image_path);
			bgr_imgs.push_back(one_img);
			std::vector<cv::Mat> nchwMats = yolov5_infer.preProcess4Validate(bgr_imgs);
			
			yolov5_infer.infer();
			results = yolov5_infer.postProcess4Validation(0.25, 0.5f);
			printf("Num object detect: %ld\n", results.size());
			for (auto &item : results)
			{
				// left, top, right, bottom, label, confident
				cv::rectangle(one_img, cv::Point(item[0], item[1]), cv::Point(item[2], item[3]), cv::Scalar(0, 255, 0), 2,
							  16);
			}
			auto end0 = std::chrono::steady_clock::now();
			std::cout << "detect time:" << std::chrono::duration_cast<std::chrono::milliseconds>(end0- start0).count() << std::endl;
}

![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/23331359/1825f059-45ac-4c14-8714-11c6907f93c4)

**Comment by ou525** [comment]
After testing, it was found that it was caused by this function preProcess4Validate. Can you help me take a look? @zerollzeng

**Comment by yunyao2011800** [comment]
> n preProcess4Validate. Can you help me take a loo

bgr_imgs.clear();

**Comment by ou525** [comment]
@yunyao2011800 Thank you; it was precisely due to this issue, and it has been resolved.
