### ISSUE TITLE
Implementation of batch size inference

### ISSUE THREAD

**Issue by ou525** [NVIDIA-AI-IOT/cuDLA-samples#25]
Thanks for sharing open source。
While there are differences in batch size inference performance mentioned in the readme, I noticed in the inference code only the provision of multiple batch variables for input images. I haven't seen the implementation of multi-batch for subsequent inference and decoding results. Is there any plan for future support?

**Comment by lynettez** [comment]
Sorry, there is no plan for that since this sample aims to show how to use cuDLA API and DLA QAT workflow.
Thanks for the feedback, anyway~
