### ISSUE TITLE
how to build tensorrt engine and use python api to run engine on dla ?

### ISSUE THREAD

**Issue by parkerpang** [NVIDIA-AI-IOT/cuDLA-samples#35]

**Comment by lynettez** [comment]
The TensorRT developer guide shows how to build tensorrt engine with DLA enabled. https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#dla_topic

When using the TensorRT Python API to deserialize an engine, simply set the DLA_Core to the desired core index, and then execute the engine normally. details can be found in https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Runtime.html

Please reach out to our TensorRT experts for further question, https://github.com/NVIDIA/TensorRT or https://forums.developer.nvidia.com/c/ai-data-science/deep-learning/tensorrt/92
