### ISSUE TITLE
Can I use this repository working on Jetson Xavier

### ISSUE THREAD

**Issue by kmsdoit** [NVIDIA-AI-IOT/cuDLA-samples#4]
I'm currently using Jetson Xavier and Jetpack is using the 5.1.2 version. Will this code work on the Jetson Xavier?

**Comment by zerollzeng** [comment]
Sorry for the late reply, the sample was developed and tested on the Orin platform.

**Comment by IamShubhamGupto** [comment]
@zerollzeng Any update on when Jetpack 6 docker containers would be available?

**Comment by zerollzeng** [comment]
Actually I don't know about it, please wait for the official announcement.

**Comment by WangFengtu1996** [comment]
About the jetson agx orin DK support?

**Comment by zerollzeng** [comment]
AFAIK JP 6.0 has been released.
