### ISSUE TITLE
For qdq translator, may exit by node scales do't match

### ISSUE THREAD

**Issue by Bobo-y** [NVIDIA-AI-IOT/cuDLA-samples#9]
![image](https://github.com/NVIDIA-AI-IOT/cuDLA-samples/assets/9928596/ab8e4976-862d-4d77-a35a-47293b0ebfbf)

As above, when use qdq translator, does this affect model precision if i force delete this "assert".

**Comment by liuanqi-libra7** [comment]
Delete this assert won't affect the accuracy. 
This check is used when the calibration method is using max, but you can also avoid this issue by setting '--calibration_type=hist'.

**Comment by Bobo-y** [comment]
Got it, thanks.
